package model;

import java.math.BigDecimal;

public class Book {

	private Integer bookId;
	// this value will be auto generated by the database
	private String bookName;
	private Writer bookWriter;
	private String bookPublisher;
	private BigDecimal bookPrice;
	private Category bookCategory;
	private String insertDate;

	public Book(String bookName, Writer bookWriter, String bookPublisher, BigDecimal bookPrice, Category bookCategory,
			String insertDate) {
		super();
		this.bookName = bookName;
		this.bookWriter = bookWriter;
		this.bookPublisher = bookPublisher;
		this.bookPrice = bookPrice;
		this.bookCategory = bookCategory;
		this.insertDate = insertDate;
	}

	public Book(Book book) {
		super();
		this.bookId = book.getBookId();
		this.bookName = book.getBookName();
		this.bookWriter = book.getBookWriter();
		this.bookPublisher = book.getBookPublisher();
		this.bookPrice = book.getBookPrice();
		this.bookCategory = book.getBookCategory();
		this.insertDate = book.getInsertDate();
	}

	public Book(Integer bookId, String bookName, Writer bookWriter, String bookPublisher, BigDecimal bookPrice,
			Category bookCategory, String insertDate) {
		super();
		this.bookId = bookId;
		this.bookName = bookName;
		this.bookWriter = bookWriter;
		this.bookPublisher = bookPublisher;
		this.bookPrice = bookPrice;
		this.bookCategory = bookCategory;
		this.insertDate = insertDate;
	}

	public Integer getBookId() {
		return bookId;
	}

	public void setBookId(int bookID) {
		this.bookId = bookID;
	}

	public String getBookName() {
		return bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	public Writer getBookWriter() {
		return bookWriter;
	}

	public void setBookWriter(Writer bookWriter) {
		this.bookWriter = bookWriter;
	}

	public String getBookPublisher() {
		return bookPublisher;
	}

	public void setBookPublisher(String bookPublisher) {
		this.bookPublisher = bookPublisher;
	}

	public Category getBookCategory() {
		return bookCategory;
	}

	public void setBookCategory(Category bookCategory) {
		this.bookCategory = bookCategory;
	}

	public BigDecimal getBookPrice() {
		return bookPrice;
	}

	public void setBookPrice(BigDecimal bookPrice) {
		this.bookPrice = bookPrice;
	}

	public String getInsertDate() {
		return insertDate;
	}

	public void setInsertDate(String insertDate) {
		this.insertDate = insertDate;
	}

}