package model;

import java.sql.Date;

public class User {

	private Integer iduser;
	// this value will be auto generated by the database
	private String username;
	private String password;
	private String gender;
	
	Date birthDate;

	public User(String username, String password, String gender, Date birthDate) {
		super();
		this.username = username;
		this.password = password;
		this.gender = gender;
		this.birthDate = birthDate;
	}

	public User(String username, String password) {
		super();
		this.username = username;
		this.password = password;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	String getUserName() {
		return this.username;
	}

	public int getIduser() {
		return iduser;
	}

	public String getUsername() {
		return username;
	}

	public String getPassword() {
		return password;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	public Date getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

}