package model;

import java.sql.Date;

import dao.WriterDao;
import dao.WriterDaoImpl;

public class Writer {

	private Integer writerId;
	// this value will be auto generated by the database
	private String writerName;
	private String gender;

	

	private Date birthDate;

	public Writer(Integer writerId, String writerName, String gender, Date birthDate) {
		super();
		this.writerId = writerId;
		this.writerName = writerName;
		this.gender = gender;
		this.birthDate = birthDate;
	}

	public Writer(String writerName, String gender, Date birthDate) {
		super();
		this.writerName = writerName;
		this.gender = gender;
		this.birthDate = birthDate;
	}

	public Writer(String writerName) {
		super();
		this.writerName = writerName;
	}

	public Writer(Integer writerId) {
		super();
		this.writerId = writerId;
		WriterDao writerDao = new WriterDaoImpl();
		Writer writer = writerDao.getWriter(writerId);
		this.writerName = writer.getWriterName();
		this.gender = writer.getGender();
		this.birthDate = writer.getBirthDate();
	}

	public String getWriterName() {
		return writerName;
	}

	public void setWriterName(String writerName) {
		this.writerName = writerName;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Integer getWriterId() {
		return writerId;
	}

}
